//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XAtlasSharp {

public class UvMeshDecl : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal UvMeshDecl(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(UvMeshDecl obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~UvMeshDecl() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          XAtlasPINVOKE.delete_UvMeshDecl(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public System.IntPtr VertexUvData {
    set {
      XAtlasPINVOKE.UvMeshDecl_VertexUvData_set(swigCPtr, new System.Runtime.InteropServices.HandleRef(null, value));
    } get{System.IntPtr res = XAtlasPINVOKE.UvMeshDecl_VertexUvData_get(swigCPtr); ; return res;}
  }

  public System.IntPtr IndexData {
    set {
      XAtlasPINVOKE.UvMeshDecl_IndexData_set(swigCPtr, new System.Runtime.InteropServices.HandleRef(null, value));
    } get{System.IntPtr res = XAtlasPINVOKE.UvMeshDecl_IndexData_get(swigCPtr); ; return res;}
  }

  public System.IntPtr FaceMaterialData {
    set {
      XAtlasPINVOKE.UvMeshDecl_FaceMaterialData_set(swigCPtr, new System.Runtime.InteropServices.HandleRef(null, value));
    } get{System.IntPtr res = XAtlasPINVOKE.UvMeshDecl_FaceMaterialData_get(swigCPtr); ; return res;}
  }

  public uint VertexCount {
    set {
      XAtlasPINVOKE.UvMeshDecl_VertexCount_set(swigCPtr, value);
    } 
    get {
      uint ret = XAtlasPINVOKE.UvMeshDecl_VertexCount_get(swigCPtr);
      return ret;
    } 
  }

  public uint VertexStride {
    set {
      XAtlasPINVOKE.UvMeshDecl_VertexStride_set(swigCPtr, value);
    } 
    get {
      uint ret = XAtlasPINVOKE.UvMeshDecl_VertexStride_get(swigCPtr);
      return ret;
    } 
  }

  public uint IndexCount {
    set {
      XAtlasPINVOKE.UvMeshDecl_IndexCount_set(swigCPtr, value);
    } 
    get {
      uint ret = XAtlasPINVOKE.UvMeshDecl_IndexCount_get(swigCPtr);
      return ret;
    } 
  }

  public int IndexOffset {
    set {
      XAtlasPINVOKE.UvMeshDecl_IndexOffset_set(swigCPtr, value);
    } 
    get {
      int ret = XAtlasPINVOKE.UvMeshDecl_IndexOffset_get(swigCPtr);
      return ret;
    } 
  }

  public IndexFormat IndexFormat {
    set {
      XAtlasPINVOKE.UvMeshDecl_IndexFormat_set(swigCPtr, (int)value);
    } 
    get {
      IndexFormat ret = (IndexFormat)XAtlasPINVOKE.UvMeshDecl_IndexFormat_get(swigCPtr);
      return ret;
    } 
  }

  public UvMeshDecl() : this(XAtlasPINVOKE.new_UvMeshDecl(), true) {
  }

}

}
