//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XAtlasSharp {

public class Vertex : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Vertex(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Vertex obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Vertex() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          XAtlasPINVOKE.delete_Vertex(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int AtlasIndex {
    set {
      XAtlasPINVOKE.Vertex_AtlasIndex_set(swigCPtr, value);
    } 
    get {
      int ret = XAtlasPINVOKE.Vertex_AtlasIndex_get(swigCPtr);
      return ret;
    } 
  }

  public int ChartIndex {
    set {
      XAtlasPINVOKE.Vertex_ChartIndex_set(swigCPtr, value);
    } 
    get {
      int ret = XAtlasPINVOKE.Vertex_ChartIndex_get(swigCPtr);
      return ret;
    } 
  }

  public float[] Uv {
    set {
      XAtlasPINVOKE.Vertex_Uv_set(swigCPtr, ref value[0]);
    } 
    get
    {
        var _temp = new float[2];
        System.Runtime.InteropServices.Marshal.Copy(XAtlasPINVOKE.Vertex_Uv_get(swigCPtr), _temp, 0, 2);
        return _temp;
    }

  }

  public uint Xref {
    set {
      XAtlasPINVOKE.Vertex_Xref_set(swigCPtr, value);
    } 
    get {
      uint ret = XAtlasPINVOKE.Vertex_Xref_get(swigCPtr);
      return ret;
    } 
  }

}

}
